- name: Restart MariaDB
  service:
    name: mariadb
    state: restarted

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded

- name: Restart ERPNext services
  systemd:
    name: "{{ service_base }}-{{ item }}.service"
    state: restarted
  loop:
    - web
    - socketio
    - worker